# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: mydashboard_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5440:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7.0-alpine
    container_name: mydashboard_redis
    ports:
      - '6390:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  pgdata:
  redis_data:
